version: "2"
plugins:
  fixme:
    enabled: true
  markdownlnt:
    enabled: true
  editorconfig:
    enabled: true
    channel: beta
    config:
      editorconfig: .editorconfig
exclude_patterns:
  - "**/*.png"
